---
title: "Teaching"
toc: true 
link-external-newwindow: true
---

## Oregon State University (Instructor - Online)
Sustainable Living - Practice and Policy (x2) </br>
Politics of Developing Nations (x3)

## University of Illinois at Chicago (Teaching Assistant)
Principles of Microeconomics(Undergraduate) </br>
Principles of Macroeconomics(Undergraduate) 

## Portland State University (Teaching Assistant)
Advanced Econometrics(Graduate) </br>
Advanced Applied Econometrics(Graduate) </br>
Health Economics(Graduate/undergraduate) </br>
Women in the Economy(Graduate/undergraduate) </br>
Multinational Enterprises(Graduate/undergraduate)</br>
Labor Economics and Industrial Relations(Graduate/Undergraduate) </br>
Intermediate Microeconomics(Undergraduate) </br>
Principles of Microeconomics(Undergraduate) </br>
Intermediate Macroeconomics(Undergraduate) </br>
Principles of Macroeconomics(Undergraduate) 

## Trainings
Push Button Replication (Computational Reproducibility) </br>
Research Transparency and Open Science Practices </br>
Impact Evaluation Methodologies using Stata
